name: reward

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.5
  - pytorch>=1.0
  - numpy
  - scipy
  - opencv
  - pip
  - pip:
      - pytest
      - pyyaml
      - sphinx
      - tensorboardX
      - tqdm
      - fire
      - boltons
