name: torchrl

channels:
  - pytorch
  - conda-forge
  - anaconda

dependencies:
  - python>=3.5
  - pytorch>=0.4
  - numpy
  - scipy
  - opencv
  - pip
  - swig
  - pip:
      - pyyaml
      - sphinx
      - 'gym[all]'
      - pandas
      - tensorflow
      - tensorboardX
