name: reward

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.5
  - pytorch>=0.4
  - numpy
  - scipy
  - opencv
  - pip
  - pip:
      - pytest
      - pyyaml
      - sphinx
      - tensorflow
      - tensorboardX
      - tqdm
